export const INCREMENT_LIKES = "INCREMENT_LIKES";
export const DECREMENT_LIKES = "DECREMENT_LIKES";

export const INPUT_TEXT = "INPUT_TEXT";

export const COMMENT_CREATE = "COMMENT_CREATE";
export const COMMENT_UPDATE = "COMMENT_UPDATE";
export const COMMENT_REMOVE = "COMMENT_REMOVE";
export const COMMENTS_ADD = "COMMENTS_ADD";

export const LOADER_DISPALY_ON = "LOADER_DISPALY_ON";
export const LOADER_DISPALY_OFF = "LOADER_DISPALY_OFF";

export const ERROR_DISPLAY_ON = "ERROR_DISPLAY_ON";
export const ERROR_DISPLAY_OFF = "ERROR_DISPLAY_OFF";